/**
 * Turn the built client bundle into the self-registering module the host serves.
 *
 * The host's browser loader does not import a plugin's client as an ES module.
 * It evaluates a script that calls `window.__ModuleLoader__.load({ id, factory })`
 * and expects the factory to behave like CommonJS: it receives a `require` that
 * resolves the host's own modules (`react`, `react/jsx-runtime`) and returns the
 * plugin's exports.
 *
 * So the last build step is a transform, not a copy: wrap `lib/client.cjs` in
 * that envelope, and refuse loudly if the intermediate is missing or does not
 * look like CommonJS. Shipping an unwrapped ESM file here produces a plugin that
 * builds, packs, and silently never appears in the UI.
 *
 * Usage (from `pnpm run build`): `node scripts/wrap-client.mjs`
 */
import { existsSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'

/** Built CommonJS intermediate produced by tsdown.client.config.ts. */
const SOURCE = 'lib/client.cjs'

/** The file the host actually serves. */
const TARGET = 'lib/client.js'

/**
 * Declaration file the CJS build emits, and the name `exports` promises.
 *
 * tsdown suffixes declarations with the module format, so a CJS build writes
 * `client.d.cts` while the manifest declares `./lib/client.d.ts`. Renaming here
 * keeps the promise rather than bending the manifest to the tool's default.
 */
const DTS_SOURCE = 'lib/client.d.cts'
const DTS_TARGET = 'lib/client.d.ts'

/** Marker every CommonJS bundle carries; its absence means the wrong input. */
const CJS_MARKER = 'exports'

/** Indent one line by `depth` tab stops. */
function indentLine(line, depth) {
	const padding = '\t'.repeat(depth)
	return line === '' ? '' : `${padding}${line}`
}

/**
 * Read the package name, which is the loader id the host keys this module by.
 * @returns The `name` field of the repository's package.json.
 */
function readPackageName() {
	const manifest = JSON.parse(readFileSync('package.json', 'utf8'))
	if (typeof manifest.name !== 'string' || manifest.name === '') {
		throw new Error('package.json has no name to use as the ModuleLoader id')
	}
	return manifest.name
}

/**
 * Wrap the CommonJS intermediate and write the served artifact.
 * @returns Nothing; throws on a malformed input.
 */
function main() {
	const name = readPackageName()

	let body
	try {
		body = readFileSync(SOURCE, 'utf8')
	} catch (error) {
		throw new Error(`cannot read ${SOURCE}: ${error.message}. Run the client build first.`)
	}

	if (!body.includes(CJS_MARKER)) {
		throw new Error(`${SOURCE} does not look like CommonJS; check the client build format`)
	}

	const indented = body.split('\n').map((line) => indentLine(line, 3)).join('\n')
	const wrapped = [
		'/* Generated by scripts/wrap-client.mjs — do not edit. */',
		'window.__ModuleLoader__.load({',
		`\tid: ${JSON.stringify(name)},`,
		'\tfactory: (require) => {',
		'\t\tconst module = { exports: {} };',
		'\t\tconst exports = module.exports;',
		indented,
		'\t\treturn module.exports;',
		'\t},',
		'});',
		'',
	].join('\n')

	writeFileSync(TARGET, wrapped)
	rmSync(SOURCE)

	// The declaration is promised by `exports`, so its absence is a broken
	// manifest rather than a cosmetic gap.
	if (existsSync(DTS_SOURCE)) {
		renameSync(DTS_SOURCE, DTS_TARGET)
	}

	process.stdout.write(`wrap-client: ${SOURCE} -> ${TARGET} (id ${name})\n`)
}

main()
